library("rmongodb")
library("tm")
mgl=mongo.create()
data<-mongo.find.all(mgl, "test_database.test_collection", "{}")
data2<-subset(x=data, select="content")
ds <- DataframeSource(data2)

SAcorpus<-VCorpus(ds)
SAcorpus<-tm_map(SAcorpus, stripWhitespace)
SAcorpus<-tm_map(SAcorpus, removePunctuation)
SAcorpus<-tm_map(SAcorpus, content_transformer(tolower))
SAcorpus<-tm_map(SAcorpus, removeWords, stopwords("english"))
SAcorpus<-tm_map(SAcorpus, stemDocument)
dtm=DocumentTermMatrix(SAcorpus)
findFreqTerms(dtm, 50)
